FROM node:14-buster-slim

# Configure npm
RUN npm set progress=false && npm config set depth 0

# Set working directory
WORKDIR /app

RUN npm -g config set user root 

# Install dependencies
RUN npm install typescript@3.6.2 \
    && npm install grpc-tools@1.7.0 \
    && npm install grpc_tools_node_protoc_ts@5.0.1

    
# copy the entire project
COPY . .

RUN npm run protogen